type: app
description: Default stackfile usecase description
# template used to create the project
template: afcl-json-serialization-tools/<template-name>
inputs:
  some_input: value
# list of plugins to be applied after project creation
plugins:
  - plugin: afcl-json-serialization-tools/<plugin-name>
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
